/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DigitalSignageIndexRouteImport } from './routes/digital-signage/index'
import { Route as DigitalSignageDisplayRouteImport } from './routes/digital-signage/display'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalSignageIndexRoute = DigitalSignageIndexRouteImport.update({
  id: '/digital-signage/',
  path: '/digital-signage/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalSignageDisplayRoute = DigitalSignageDisplayRouteImport.update({
  id: '/digital-signage/display',
  path: '/digital-signage/display',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-signage/display': typeof DigitalSignageDisplayRoute
  '/digital-signage/': typeof DigitalSignageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-signage/display': typeof DigitalSignageDisplayRoute
  '/digital-signage': typeof DigitalSignageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-signage/display': typeof DigitalSignageDisplayRoute
  '/digital-signage/': typeof DigitalSignageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/digital-signage/display' | '/digital-signage/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/digital-signage/display' | '/digital-signage'
  id: '__root__' | '/' | '/digital-signage/display' | '/digital-signage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalSignageDisplayRoute: typeof DigitalSignageDisplayRoute
  DigitalSignageIndexRoute: typeof DigitalSignageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-signage/': {
      id: '/digital-signage/'
      path: '/digital-signage'
      fullPath: '/digital-signage/'
      preLoaderRoute: typeof DigitalSignageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-signage/display': {
      id: '/digital-signage/display'
      path: '/digital-signage/display'
      fullPath: '/digital-signage/display'
      preLoaderRoute: typeof DigitalSignageDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalSignageDisplayRoute: DigitalSignageDisplayRoute,
  DigitalSignageIndexRoute: DigitalSignageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
